services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini:ro

    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9003:9003" # Xdebug
    expose:
      - "9000" # PHP-FPM
    environment:
      APP_ENV: dev

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"  # host:container
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
