version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    environment:
      APP_ENV: dev
    expose:
      - "9000"

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"  # host:container
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
