version: "3.9"

services:
  php:
    image: your-ghcr-namespace/your-app:latest  # REPLACE with your actual image
    container_name: symfony-php
    working_dir: /var/www/html
    environment:
      APP_ENV: prod
    expose:
      - "9000"

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
