name: CI (PR)

on:
  pull_request:
    branches: [ master ]

jobs:
  quality:
    defaults:
      run:
        working-directory: ./app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_pgsql, intl

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHP CS Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=1G

      - name: Run PHPUnit
        run: vendor/bin/phpunit --testdox
