name: CI (PR)

on:
  pull_request:
    branches: [ master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_pgsql, intl

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run Lint (phpstan + fixer + rector dry-run)
        run: composer lint

      - name: Run PHPUnit
        run: composer test
